### ISSUE TITLE
The CocoaPods spec has stopped working for me. . . . 

### ISSUE THREAD

**Issue by jasperblues** [biasedbit/BBHTTP#11]
Get this: 

!] git remote update

Fetching origin
fatal: https://github.com/brunodecarvalho/BBHotpotato/info/refs?service=git-upload-pack not found: did you run git update-server-info on the server?

error: Could not fetch origin

**Comment by biasedbit** [comment]
Yeah I renamed the repo; it's now `git@github.com:brunodecarvalho/BBHTTP.git` (or https://github.com/brunodecarvalho/BBHTTP if you prefer HTTPS).
