### ISSUE TITLE
Set POST data from a dictionary?

### ISSUE THREAD

**Issue by ryanmasondavies** [biasedbit/BBHTTP#16]
I like the direction this project is going. Is it possible to set POST key-value pairs from a dictionary? E.g for [tweeting](https://dev.twitter.com/docs/api/1.1/post/statuses/update) against the Twitter REST API.

**Comment by biasedbit** [comment]
Definitely! Subject to my (extremely limited) availability over the next week but it's part of the plan.

**Comment by ryanmasondavies** [comment]
Great! Anything I can help with? I'd like to use this for my current project, so sooner the better. I can submit a pull request if you're willing to consider it.

Also what do you think about chaining response handlers? For me, composition always wins over inheritance. It would open up a doorway to some pretty powerful stuff.

A good example would be chaining a JSON parser to a responder which updates values on some model. The client wouldn't need to know about parsing JSON. E.g:

```
Request --> Selective Discarder --> JSON Parser --> Model Updater
```

The client would then join the dots, fire a request, and that's it. Very similar to Apple's chain of responsibility, and to the Decorator design pattern. Progress handling and error handling might also benefit from a similar pattern.

Edit: after a quick review of response handlers, this may have to remain a pipe dream.

**Comment by biasedbit** [comment]
That'd be awesome! I reckon it won't be too hard, you'll just need to expose a method on `BBHTTPRequest` (somewhere around [here](https://github.com/brunodecarvalho/BBHTTP/blob/master/BBHTTP/BBHTTPRequest.h#L222)):

``` objc
- (BOOL)setUploadFormData:(NSDictionary*)formData;
```

And implement it to do the following:
1. Convert the dictionary to `NSData` (create a `NSString` with the concatenated url-encoded key-value pairs)
2. Call `setUploadData:withContentType:` passing, as arguments, the `NSData` created on 1. and `application/x-www-form-urlencoded` as the content type.

From there on it'll be treated just like any other in-memory data upload.

> Also what do you think about chaining response handlers

Let's open another pull request and discuss it there, I find the idea very interesting.

**Comment by ryanmasondavies** [comment]
I've forked the project and will try to get to it when I can. :+1:
