### ISSUE TITLE
Keep alive support?

### ISSUE THREAD

**Issue by dbainbridge** [biasedbit/BBHTTP#18]
Can you comment on support for keep-alive HTTP connections on OS X using BBHTTP?   From my limited testing it appears NSURLConnection on OS X opens and closes a connection on every call.  I know libcurl supports keep alive so I was wondering if this ability  is accessible in BBHTTP?

**Comment by biasedbit** [comment]
BBHTTP will use keep-alive unless otherwise specified. Connections will remain open and will be reused on subsequent requests.

I believe `NSURLConnection` also respects the keep-alive behavior.
