### ISSUE TITLE
Link to API docs is wrong

### ISSUE THREAD

**Issue by jasperblues** [biasedbit/BBHTTP#20]
Link is: 

http://jasperblues.github.io/BBHotpotato/api/index.html

Should be your name there. 

Also - you need to run the script to publish the docs or have a CI server do it.

**Comment by jasperblues** [comment]
Can use my CI server, if you like.

**Comment by biasedbit** [comment]
I think we can skip this now that the docs are up on cocoadocs.org, right?

**Comment by jasperblues** [comment]
Yes, maybe easier just to remove the link on the GH page. 

Jasper Blues
Landline: +63.2.826.2489
Skype: jasperblues
LinkedIn Twitter
