### ISSUE TITLE
Its not clear what BBHTTPResponse.content property is

### ISSUE THREAD

**Issue by jasperblues** [biasedbit/BBHTTP#23]
I want my response as NSData . . . reading the docs shows content type is 'id'. . .this is confusing.

**Comment by biasedbit** [comment]
The content type of the response will be whatever the response content handler produces so it can be NSData, UIImage, or any other object.

Since objc has no generics, it has to be this way.

**Comment by jasperblues** [comment]
How about just adding some info in the API docs. . . What is the default content handler?

**Comment by jasperblues** [comment]
PS: When I say 'confusing' - its still way easier to come to grips with than AFNetworking!

**Comment by jasperblues** [comment]
How about having some ResponseContent classes?

DefaultResponseContent   //content property is typed to NSData

Then, In setup you could :

[setResponseContentClass:[BBImageResponseContent class]]  //Content property is typed to UIImage

This way you have: 
- Strong typing that you can look up in the API docs. . . 
- Just two lines up in the setUp block, you can see what kind of response you'll be getting. 

This way it should be possible to drive the API with IDE code completion without having to remember the details or read the docs. . . 

(Just a random idea).

**Comment by jasperblues** [comment]
Ah, OK. . . I can see now that it pretty much already works as per my suggestion above. . . Except that the short-hand API obfuscates this a bit. . .

**Comment by biasedbit** [comment]
It really depends on the response content handler. I'd rather have the user provide a response content handler than pass a class that will later map to a response content handler. Seems more straightforward.

Thanks for the feedback.
