### ISSUE TITLE
Publish API docs

### ISSUE THREAD

**Issue by jasperblues** [biasedbit/BBHTTP#4]
Hi! 

Nice lib! How about publishing the API docs on the github page? I use a script to get my build server to do it. Happy to share.

**Comment by biasedbit** [comment]
Howdy, that sounds like a nice idea. Which docs do you mean, the ones generated with appledoc or the ones in the Wiki?

**Comment by jasperblues** [comment]
I mean the ones generated by Appledoc. I publish API docs as well as test reports and code coverage reports to my project's github here www.typhoonframework.org

It's a frankenbuild type script that mixes some java, ruby, shell script, and Linux tools but its solid, compact and works. Happy to set it up for your project for you. .. (Might use your lib in the sample app for mine too)

**Comment by biasedbit** [comment]
I would definitely be interested in that!

**Comment by jasperblues** [comment]
Coolio, I should have some time to do it tomorrow. (Friday night here now). Expect a pull request in next 24 hours. . . Just API docs? No test target in ur project? 

Could also include building libCurl in that script (lipo, etc) and publish it to github as well. .. This would allow getting your lib via CocoaPods (see my other issue ) . . .or you familiar with CocoaPods? It's a really nice library manager. ... Www.cocoapods.org

**Comment by biasedbit** [comment]
The curl binary I use on BBHTTP is built with [this repo](https://github.com/brunodecarvalho/curl-ios-build-scripts) so should probably be done there.

I'm familiar with CocoaPods although I don't use it myself &mdash; I'm quite picky with the project setup and I personally dislike how it creates the workspace. Wouldn't mind making it available to everyone who uses CocoaPods, though. Mind opening up an issue for that?

**Comment by jasperblues** [comment]
I've personally grown to like it . . (hence the suggestion) . . though I wasn't too fond of workspaces myself, at first. 

 It would be no problem to publish both repos to cocoapods and set up a transitive dependency (to use the funky term) from bbhotpotatoe to the podified libCurl. . .will modify the issue that I created to " allow fetching from cocoapods" . . .

**Comment by biasedbit** [comment]
So I tried setting up the podspec for BBHTTP but I'm having a bit of a hard time figuring out how to copy over the libcurl binaries. It's at _Project/BBHTTP.podspec_ but it's obviously broken.

My goal is to avoid marking curl's headers as source files, that is, stuff in _BBHTTP/_ would be the sources and then  we'd configure the header search paths and library search paths via the `spec.<os>.xcconfig`, something like this:

``` ruby
  s.osx.xcconfig = {
    "HEADER_SEARCH_PATHS" => '"<???>/External/libcurl.OSX"',
    "LIBRARY_SEARCH_PATHS" => '"<???>/External/libcurl.OSX"'
  }
```

I usually avoid importing curl's headers files as source files in my projects because curl's OSX and iOS headers aren't compatible (for OSX they are 64bit, for iOS they are 32bit) and that'd force me to have two projects (one for OSX and other for iOS). Hence my attempt to avoid marking them as source (on the podspec) and trying to use xcode's `HEADER_SEARCH_PATHS` instead. Does this make sense to you?

**Comment by jasperblues** [comment]
Oh, . . . I sent some emails about it, but didn't forward them on, as I thought I would be handling this issue. Here, let me paste in the details: 

Justin R Miller says: "you can see a way to do this with the MapBox spec: 

https://github.com/CocoaPods/Specs/blob/master/MapBox/0.5.2/MapBox.podspec

Check out the Proj4 static library there. It's pre-built in our source tree (though source is included for the adventurous) because this sub-project never changes and takes longer than the main pod to build. In particular I had to use the preserve_paths bit to not have it deleted from the pod's files. "

**Comment by biasedbit** [comment]
Got it, thanks. You can now try this spec by adding:

``` ruby
pod "BBHTTP", :git => "https://github.com/brunodecarvalho/BBHotpotato"
```

Lemme know how it works for you.

**Comment by jasperblues** [comment]
Trying now. . . . . sorry for the long delay. . . .

**Comment by jasperblues** [comment]
By the way: I think the spec name should match the github name exactly. . . (this is also a requirement for the main CocoaPods repo).

**Comment by jasperblues** [comment]
First attempt got this - never seen it b4: 

Resolving dependencies for target `default' (iOS 4.3)
-> Pre-downloading: 'BBHTTP'
[!] git clone  --mirror "https://github.com/brunodecarvalho/BBHotpotato" "/Users/jblues/Library/Caches/CocoaPods/Git/80cb7d4e47c81f7bbd1741506baea269c603a38f"

Cloning into bare repository '/Users/jblues/Library/Caches/CocoaPods/Git/80cb7d4e47c81f7bbd1741506baea269c603a38f'...
error: RPC failed; result=18, HTTP code = 200

fatal: The remote end hung up unexpectedly

fatal: early EOF

fatal: recursion detected in die handler

**Comment by jasperblues** [comment]
2nd attempt worked, but I got '[!] BBHTTP (0.9.2) is not compatible with iOS 4.3." . . . . updating my Podfile. . . . (reading CocoaPods docs)

**Comment by jasperblues** [comment]
Installed. . .. writing a test case :)

**Comment by biasedbit** [comment]
> 2nd attempt worked, but I got '[!] BBHTTP (0.9.2) is not compatible with iOS 4.3." . . . . updating my Podfile. . . . (reading CocoaPods docs)

Yup, this BBHTTP is limited to iOS 5+ and OSX 10.7+

I think I'll rename and go with BBHTTP instead of BBHotpotato... Sounds a bit silly :)

**Comment by jasperblues** [comment]
Regarding name: I was going to say that either is fine as long as the CocoaPods spec matches (so you can search in CocoaPods). . . .but then I noticed that I didn't know how to spell potato properly its just not a word that I commonly write!). . . . so that made it hard to Google .. . . on the other hand BBHTTP is a lot of letters. . .

**Comment by jasperblues** [comment]
Works - now using BBHTTP instead of LRResty as my http stack. 

Raised a new pull request re API docs. . . . (somehow this ticket got bastardized into a discussion). . .
