### ISSUE TITLE
Can't execute request

### ISSUE THREAD

**Issue by jasperblues** [biasedbit/BBHTTP#7]
Tried the following test case: 

```
__block NSString* message;
[[BBHTTPRequest getResource:@"http:/www.google.com"] execute:^(BBHTTPResponse* r)
{
    NSLog(@"Finished: %u %@ -- received %u bytes of '%@'.", r.code, r.message, r.contentSize, r[@"Content-Type"]);
    message = r.message;
} error:^(NSError* e)
{
    NSLog(@"Request failed: %@", [e localizedDescription]);
}];

assertWillHappen(message != nil);
```

Expected it to pass, but got this response: 

2013-03-18 14:10:02.684 otest[8577:707] **\* Assertion failure in -[BBHTTPRequest setValue:forHeader:], /Users/jblues/Infraxis/mobile/iOS/Pods/BBHTTP/BBHTTP/BBHTTPRequest.m:269

value cannot be nil
Unknown.m:0: error: -[ClientTests test_some_http] : value cannot be nil

**Comment by biasedbit** [comment]
`@"http:/www.google.com"` :p

Probably needs a better message there...

**Comment by biasedbit** [comment]
What are you using for the tests here, Kiwi? (basing my assumption on `assertWillHappen()`)

If so, kickass, Kiwi is fantastic :+1:

**Comment by jasperblues** [comment]
Indeed Kiwi is great, but just plain OCUnit for the test.. . . assertWillHappen is just a simple macro - use it to wait for a condition and then proceed with normal assertions (using OCHamcrest in this case). 

For asynch testing there's also expecta (which is a matching library). 

I've included the macro in my DI framework here: https://github.com/jasperblues/Typhoon/wiki/Configuration-Management-%26-Testing   . . . (plan to put a few more integration test tools in, but so far this is the only one).

**Comment by jasperblues** [comment]
Ok, noted the typo! . . . Yes a better message would help a lot. . . will add and send a pull request. . . . after that - ready to push to main CocoaPods repo? 

Also, I've promised a pull request with script to publish API doc to your GH page. . . . coming. . . (sorry for long delay. . . had to wait until next project to try BBHotPotatoe). .

**Comment by jasperblues** [comment]
Actually, it would be easier if you added the more descriptive error message on your end. . . . otherwise I have a long loop in order to test -> fork / pull-request / new project / etc. . . . 

. . . I did contribute (via pull request) publishing API docs to the GH page.
