### ISSUE TITLE
Method names

### ISSUE THREAD

**Issue by jasperblues** [biasedbit/BBHTTP#8]
Instead of createResource/getResource, etc . . . how about using just get/post/put . . 

I'm using the library for SOAPish type services and it certainly feels more natural in this case (I know exactly what I'm gonna get without reading docs). . . at the same time, in changing the method names I don't think it would hinder the experience when using the library for proper REST services. . . .what do you think?

**Comment by biasedbit** [comment]
I originally had them under those names but they didn't respect Cocoa coding conventions nor did I feel they were conceptually correct.

I ended up going with names that come closer to a REST approach as I'm far fonder of it than SOAP :)

**Comment by jasperblues** [comment]
Of course I don't think you'd find to many people who like soap more than rest!! .... but the issue is the user now has to guess which method name corresponds to which http method . . . 

The library that I used before bbhotpotato just used the names in lower case like so: 

http://projects.lukeredpath.co.uk/resty/documentation.html

[[LRResty client] put:@"http://www.example.com" payload:@"This is the request body"
           withBlock:^(LRRestyResponse *response){}];

I personally think it would speed getting started . .  . .either way its still a great lib.

**Comment by biasedbit** [comment]
I completely understand and I agree to some extent, that's why they were originally named like that until [this commit](https://github.com/brunodecarvalho/BBHTTP/commit/5b3857147353d18de62cb0d0eac4c086cdb75187).

I just felt they were neither following Cocoa coding conventions nor correctly mapping to REST concepts so I just "followed the heart" :)

**Comment by jasperblues** [comment]
Fair enough. . . how about instead using the API docs to indicate which HTTP method will be used? . . . Maybe this way we can all have our cake ant eat it too. .. (Do they have that expression where you live?)

**Comment by biasedbit** [comment]
Yep, updating the docs to include that info would be perfect!

Nope, I don't think we have that expression. How's it written in your native language? I'll just start throwing it around randomly when talking with friends haha :)

**Comment by jasperblues** [comment]
I think its a British expression - it means "best of both worlds" , which is an American expression coined originally by a lady from the planet Argon. In our native Argonian it is pronounced: 

"ahck phlewt fleagha!"

**Comment by biasedbit** [comment]
I'll take that last one to use in parties!

**Comment by mikeabdullah** [comment]
The use of `get` is pretty un-Cocoa-like. `get` is reserved for methods which return a result by reference.

**Comment by jasperblues** [comment]
Oh - good point! 

I overlooked this when it was 'get' . . . with a bunch of blocks following. . . but, still. . . I never like seeing methods called 'getXXX' in Java, when they're not a property accessory.
